/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package interuserface;

import business.PersonProfile;

/**
 *
 * @author Whisley
 */
public class MainJFrame extends javax.swing.JFrame {

    /**
     * Creates new form MainJFrame
     */
    public MainJFrame() {
        initComponents();
        personProfile = new PersonProfile();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        demoJTabbedPane = new javax.swing.JTabbedPane();
        demoJSplitPane = new javax.swing.JSplitPane();
        createDemoJPanel = new javax.swing.JPanel();
        firstnameJLabel = new javax.swing.JLabel();
        lastnameJLabel = new javax.swing.JLabel();
        doeJLabel = new javax.swing.JLabel();
        ageJLabel = new javax.swing.JLabel();
        heightJLabel = new javax.swing.JLabel();
        weightJLabel = new javax.swing.JLabel();
        phoneJLabel = new javax.swing.JLabel();
        ssnJLabel = new javax.swing.JLabel();
        submitJButton = new javax.swing.JButton();
        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jTextField3 = new javax.swing.JTextField();
        jTextField4 = new javax.swing.JTextField();
        jTextField5 = new javax.swing.JTextField();
        jTextField6 = new javax.swing.JTextField();
        jTextField7 = new javax.swing.JTextField();
        firstnameJTextField = new javax.swing.JTextField();
        viewDemoJPanel = new javax.swing.JPanel();
        firstnameJLabel1 = new javax.swing.JLabel();
        lastnameJLabel1 = new javax.swing.JLabel();
        doeJLabel1 = new javax.swing.JLabel();
        ageJLabel1 = new javax.swing.JLabel();
        heightJLabel1 = new javax.swing.JLabel();
        weightJLabel1 = new javax.swing.JLabel();
        phoneJLabel1 = new javax.swing.JLabel();
        ssnJLabel1 = new javax.swing.JLabel();
        firstnameJTextField1 = new javax.swing.JTextField();
        jTextField26 = new javax.swing.JTextField();
        jTextField28 = new javax.swing.JTextField();
        jTextField29 = new javax.swing.JTextField();
        jTextField30 = new javax.swing.JTextField();
        jTextField31 = new javax.swing.JTextField();
        jTextField32 = new javax.swing.JTextField();
        jTextField63 = new javax.swing.JTextField();
        addressJTabbedPane = new javax.swing.JTabbedPane();
        addressJSplitPane = new javax.swing.JSplitPane();
        createAddressJPanel = new javax.swing.JPanel();
        streetJLabel = new javax.swing.JLabel();
        cityJLabel = new javax.swing.JLabel();
        stateJLabel = new javax.swing.JLabel();
        zipcodeJLabel = new javax.swing.JLabel();
        submitJButton1 = new javax.swing.JButton();
        jTextField17 = new javax.swing.JTextField();
        jTextField18 = new javax.swing.JTextField();
        jTextField20 = new javax.swing.JTextField();
        jTextField24 = new javax.swing.JTextField();
        viewAddressJPanel = new javax.swing.JPanel();
        streetJLabel1 = new javax.swing.JLabel();
        jTextField33 = new javax.swing.JTextField();
        cityJLabel1 = new javax.swing.JLabel();
        jTextField34 = new javax.swing.JTextField();
        stateJLabel1 = new javax.swing.JLabel();
        jTextField35 = new javax.swing.JTextField();
        zipcodeJLabel1 = new javax.swing.JLabel();
        jTextField36 = new javax.swing.JTextField();
        savingJTabbedPane = new javax.swing.JTabbedPane();
        savingJSplitPane = new javax.swing.JSplitPane();
        createSavingJPanel = new javax.swing.JPanel();
        sBanknameJLabel = new javax.swing.JLabel();
        sRoutingNoJLabel = new javax.swing.JLabel();
        sAccountNoJLabel = new javax.swing.JLabel();
        sAccountBalanceJLabel = new javax.swing.JLabel();
        sAccountypeJLabel = new javax.swing.JLabel();
        submitJButton2 = new javax.swing.JButton();
        jTextField9 = new javax.swing.JTextField();
        jTextField10 = new javax.swing.JTextField();
        jTextField11 = new javax.swing.JTextField();
        jTextField12 = new javax.swing.JTextField();
        jTextField16 = new javax.swing.JTextField();
        viewSavingJPanel = new javax.swing.JPanel();
        sAccounttypeJLabel1 = new javax.swing.JLabel();
        sAccountBalanceJLabel1 = new javax.swing.JLabel();
        sAccountNoJLabel1 = new javax.swing.JLabel();
        sRoutingNoJLabel1 = new javax.swing.JLabel();
        sBanknameJLabel1 = new javax.swing.JLabel();
        jTextField37 = new javax.swing.JTextField();
        jTextField13 = new javax.swing.JTextField();
        jTextField14 = new javax.swing.JTextField();
        jTextField15 = new javax.swing.JTextField();
        jTextField38 = new javax.swing.JTextField();
        checkingJTabbedPane = new javax.swing.JTabbedPane();
        checkingJSplitPane = new javax.swing.JSplitPane();
        createCheckingJPanel = new javax.swing.JPanel();
        cBanknameJLabel = new javax.swing.JLabel();
        cRoutingNoJLabel = new javax.swing.JLabel();
        cAccountNoJLabel = new javax.swing.JLabel();
        cAccountBalanceJLabel = new javax.swing.JLabel();
        cAccountTypeJLabel = new javax.swing.JLabel();
        submitJButton4 = new javax.swing.JButton();
        jTextField45 = new javax.swing.JTextField();
        jTextField46 = new javax.swing.JTextField();
        jTextField47 = new javax.swing.JTextField();
        jTextField48 = new javax.swing.JTextField();
        jTextField49 = new javax.swing.JTextField();
        viewCheckingJPanel = new javax.swing.JPanel();
        cAccounttypeJLabel1 = new javax.swing.JLabel();
        cAccountBalanceJLabel1 = new javax.swing.JLabel();
        cAccountNoJLabel1 = new javax.swing.JLabel();
        cRoutingNoJLabel1 = new javax.swing.JLabel();
        cBanknameJLabel1 = new javax.swing.JLabel();
        jTextField50 = new javax.swing.JTextField();
        jTextField51 = new javax.swing.JTextField();
        jTextField52 = new javax.swing.JTextField();
        jTextField53 = new javax.swing.JTextField();
        jTextField54 = new javax.swing.JTextField();
        driverJTabbedPane = new javax.swing.JTabbedPane();
        driverJSplitPane = new javax.swing.JSplitPane();
        createDriverJPanel = new javax.swing.JPanel();
        licenseNoJLabel = new javax.swing.JLabel();
        issuedDateJLabel = new javax.swing.JLabel();
        expireDateJLabel = new javax.swing.JLabel();
        bloodJLabel = new javax.swing.JLabel();
        photoJLabel = new javax.swing.JLabel();
        submitJButton3 = new javax.swing.JButton();
        jTextField19 = new javax.swing.JTextField();
        jTextField21 = new javax.swing.JTextField();
        jTextField22 = new javax.swing.JTextField();
        jTextField25 = new javax.swing.JTextField();
        jTextField39 = new javax.swing.JTextField();
        viewDriverJPanel = new javax.swing.JPanel();
        photoJLabel1 = new javax.swing.JLabel();
        bloodJLabel1 = new javax.swing.JLabel();
        expireDateJLabel1 = new javax.swing.JLabel();
        issuedDateJLabel1 = new javax.swing.JLabel();
        licenseNoJLabel1 = new javax.swing.JLabel();
        jTextField40 = new javax.swing.JTextField();
        jTextField41 = new javax.swing.JTextField();
        jTextField42 = new javax.swing.JTextField();
        jTextField43 = new javax.swing.JTextField();
        jTextField44 = new javax.swing.JTextField();
        medicalJTabbedPane = new javax.swing.JTabbedPane();
        jSplitPane1 = new javax.swing.JSplitPane();
        createMedicalJPanel = new javax.swing.JPanel();
        medicalNoJLabel = new javax.swing.JLabel();
        alergy1JLabel = new javax.swing.JLabel();
        alergy2JLabel = new javax.swing.JLabel();
        alergy3JLabel = new javax.swing.JLabel();
        submitJButton5 = new javax.swing.JButton();
        jTextField55 = new javax.swing.JTextField();
        jTextField56 = new javax.swing.JTextField();
        jTextField57 = new javax.swing.JTextField();
        jTextField58 = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        medicalNoJLabel1 = new javax.swing.JLabel();
        alergy1JLabel1 = new javax.swing.JLabel();
        alergy2JLabel1 = new javax.swing.JLabel();
        alergy3JLabel1 = new javax.swing.JLabel();
        jTextField59 = new javax.swing.JTextField();
        jTextField60 = new javax.swing.JTextField();
        jTextField61 = new javax.swing.JTextField();
        jTextField62 = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jTabbedPane1.setAlignmentX(3.0F);
        jTabbedPane1.setAlignmentY(3.0F);
        jTabbedPane1.setFont(new java.awt.Font("微软雅黑", 0, 18)); // NOI18N
        jTabbedPane1.setPreferredSize(new java.awt.Dimension(200, 200));
        jTabbedPane1.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentHidden(java.awt.event.ComponentEvent evt) {
                jTabbedPane1ComponentHidden(evt);
            }
            public void componentShown(java.awt.event.ComponentEvent evt) {
                jTabbedPane1ComponentShown(evt);
            }
        });

        createDemoJPanel.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        createDemoJPanel.setMinimumSize(new java.awt.Dimension(250, 455));
        createDemoJPanel.setPreferredSize(new java.awt.Dimension(300, 455));

        firstnameJLabel.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        firstnameJLabel.setText("First Name");

        lastnameJLabel.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        lastnameJLabel.setText("Last Name");

        doeJLabel.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        doeJLabel.setText("Date of Birth");

        ageJLabel.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        ageJLabel.setText("Age");

        heightJLabel.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        heightJLabel.setText("Height");

        weightJLabel.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        weightJLabel.setText("Weight");

        phoneJLabel.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        phoneJLabel.setText("Phone Number");

        ssnJLabel.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        ssnJLabel.setText("SSN");

        submitJButton.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        submitJButton.setText("Submit");
        submitJButton.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        submitJButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                submitJButtonMouseClicked(evt);
            }
        });
        submitJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submitJButtonActionPerformed(evt);
            }
        });

        jTextField3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField3ActionPerformed(evt);
            }
        });

        jTextField6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField6ActionPerformed(evt);
            }
        });

        firstnameJTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                firstnameJTextFieldActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout createDemoJPanelLayout = new javax.swing.GroupLayout(createDemoJPanel);
        createDemoJPanel.setLayout(createDemoJPanelLayout);
        createDemoJPanelLayout.setHorizontalGroup(
            createDemoJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(createDemoJPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(createDemoJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(submitJButton, javax.swing.GroupLayout.DEFAULT_SIZE, 286, Short.MAX_VALUE)
                    .addGroup(createDemoJPanelLayout.createSequentialGroup()
                        .addGroup(createDemoJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(phoneJLabel)
                            .addComponent(weightJLabel)
                            .addComponent(doeJLabel)
                            .addComponent(lastnameJLabel)
                            .addComponent(firstnameJLabel)
                            .addComponent(ssnJLabel)
                            .addComponent(heightJLabel))
                        .addGap(18, 18, 18)
                        .addGroup(createDemoJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jTextField2, javax.swing.GroupLayout.DEFAULT_SIZE, 115, Short.MAX_VALUE)
                            .addComponent(jTextField1, javax.swing.GroupLayout.DEFAULT_SIZE, 115, Short.MAX_VALUE)
                            .addComponent(jTextField4, javax.swing.GroupLayout.DEFAULT_SIZE, 115, Short.MAX_VALUE)
                            .addComponent(jTextField3, javax.swing.GroupLayout.DEFAULT_SIZE, 115, Short.MAX_VALUE)
                            .addComponent(jTextField5, javax.swing.GroupLayout.DEFAULT_SIZE, 115, Short.MAX_VALUE)
                            .addComponent(jTextField7, javax.swing.GroupLayout.DEFAULT_SIZE, 115, Short.MAX_VALUE)
                            .addComponent(jTextField6, javax.swing.GroupLayout.DEFAULT_SIZE, 74, Short.MAX_VALUE)
                            .addComponent(firstnameJTextField)))
                    .addComponent(ageJLabel)))
        );

        createDemoJPanelLayout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {jTextField1, jTextField2, jTextField3, jTextField4, jTextField5, jTextField6, jTextField7});

        createDemoJPanelLayout.setVerticalGroup(
            createDemoJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(createDemoJPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(createDemoJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(firstnameJLabel)
                    .addComponent(firstnameJTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(createDemoJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lastnameJLabel)
                    .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(createDemoJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(doeJLabel)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(createDemoJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ageJLabel)
                    .addComponent(jTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(createDemoJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(heightJLabel)
                    .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(createDemoJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(weightJLabel)
                    .addComponent(jTextField5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(createDemoJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(phoneJLabel)
                    .addComponent(jTextField7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(createDemoJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ssnJLabel)
                    .addComponent(jTextField6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addComponent(submitJButton, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(93, Short.MAX_VALUE))
        );

        createDemoJPanelLayout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {firstnameJTextField, jTextField1, jTextField2, jTextField3, jTextField4, jTextField5, jTextField6, jTextField7});

        demoJSplitPane.setLeftComponent(createDemoJPanel);

        viewDemoJPanel.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        viewDemoJPanel.setToolTipText("");
        viewDemoJPanel.setAlignmentX(1.0F);
        viewDemoJPanel.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        viewDemoJPanel.setPreferredSize(new java.awt.Dimension(200, 455));

        firstnameJLabel1.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        firstnameJLabel1.setText("First Name");

        lastnameJLabel1.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        lastnameJLabel1.setText("Last Name");

        doeJLabel1.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        doeJLabel1.setText("Date of Birth");

        ageJLabel1.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        ageJLabel1.setText("Age");

        heightJLabel1.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        heightJLabel1.setText("Height");

        weightJLabel1.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        weightJLabel1.setText("Weight");

        phoneJLabel1.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        phoneJLabel1.setText("Phone Number");

        ssnJLabel1.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        ssnJLabel1.setText("SSN");

        firstnameJTextField1.setEnabled(false);
        firstnameJTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                firstnameJTextField1ActionPerformed(evt);
            }
        });

        jTextField26.setEnabled(false);

        jTextField28.setEnabled(false);

        jTextField29.setEnabled(false);
        jTextField29.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField29ActionPerformed(evt);
            }
        });

        jTextField30.setEnabled(false);

        jTextField31.setEnabled(false);

        jTextField32.setEnabled(false);
        jTextField32.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField32ActionPerformed(evt);
            }
        });

        jTextField63.setEnabled(false);

        javax.swing.GroupLayout viewDemoJPanelLayout = new javax.swing.GroupLayout(viewDemoJPanel);
        viewDemoJPanel.setLayout(viewDemoJPanelLayout);
        viewDemoJPanelLayout.setHorizontalGroup(
            viewDemoJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(viewDemoJPanelLayout.createSequentialGroup()
                .addGap(45, 45, 45)
                .addGroup(viewDemoJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(doeJLabel1)
                    .addComponent(phoneJLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(ssnJLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(firstnameJLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lastnameJLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(heightJLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(weightJLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(ageJLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(viewDemoJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(firstnameJTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField26, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField28, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField29, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField30, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField31, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField32, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField63, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(425, 425, 425))
        );

        viewDemoJPanelLayout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {firstnameJTextField1, jTextField26, jTextField28, jTextField29, jTextField30, jTextField31, jTextField32, jTextField63});

        viewDemoJPanelLayout.setVerticalGroup(
            viewDemoJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(viewDemoJPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(viewDemoJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(firstnameJLabel1)
                    .addComponent(firstnameJTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(viewDemoJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lastnameJLabel1)
                    .addComponent(jTextField26, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(viewDemoJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(doeJLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField63, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(viewDemoJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTextField28, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ageJLabel1))
                .addGap(18, 18, 18)
                .addGroup(viewDemoJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(heightJLabel1)
                    .addComponent(jTextField29, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(viewDemoJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(weightJLabel1)
                    .addComponent(jTextField30, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(viewDemoJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTextField31, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(phoneJLabel1))
                .addGap(18, 18, 18)
                .addGroup(viewDemoJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ssnJLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField32, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(181, Short.MAX_VALUE))
        );

        viewDemoJPanelLayout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {doeJLabel1, firstnameJTextField1, jTextField26, jTextField28, jTextField29, jTextField30, jTextField31, jTextField32, jTextField63});

        viewDemoJPanelLayout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {firstnameJLabel1, heightJLabel1, lastnameJLabel1, phoneJLabel1, weightJLabel1});

        demoJSplitPane.setRightComponent(viewDemoJPanel);

        demoJTabbedPane.addTab("tab1", demoJSplitPane);

        jTabbedPane1.addTab("Demographic Info", demoJTabbedPane);

        createAddressJPanel.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        createAddressJPanel.setEnabled(false);
        createAddressJPanel.setMinimumSize(new java.awt.Dimension(250, 455));
        createAddressJPanel.setPreferredSize(new java.awt.Dimension(300, 455));

        streetJLabel.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        streetJLabel.setText("Steet Address");

        cityJLabel.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        cityJLabel.setText("City");

        stateJLabel.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        stateJLabel.setText("State");

        zipcodeJLabel.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        zipcodeJLabel.setText("Zip Code");

        submitJButton1.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        submitJButton1.setText("Submit");
        submitJButton1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jTextField24.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField24ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout createAddressJPanelLayout = new javax.swing.GroupLayout(createAddressJPanel);
        createAddressJPanel.setLayout(createAddressJPanelLayout);
        createAddressJPanelLayout.setHorizontalGroup(
            createAddressJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(createAddressJPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(createAddressJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(submitJButton1, javax.swing.GroupLayout.DEFAULT_SIZE, 286, Short.MAX_VALUE)
                    .addGroup(createAddressJPanelLayout.createSequentialGroup()
                        .addGroup(createAddressJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(stateJLabel)
                            .addComponent(cityJLabel)
                            .addComponent(streetJLabel))
                        .addGap(23, 23, 23)
                        .addGroup(createAddressJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jTextField18, javax.swing.GroupLayout.DEFAULT_SIZE, 115, Short.MAX_VALUE)
                            .addComponent(jTextField17, javax.swing.GroupLayout.DEFAULT_SIZE, 115, Short.MAX_VALUE)
                            .addComponent(jTextField20, javax.swing.GroupLayout.DEFAULT_SIZE, 115, Short.MAX_VALUE)
                            .addComponent(jTextField24)))
                    .addComponent(zipcodeJLabel)))
        );
        createAddressJPanelLayout.setVerticalGroup(
            createAddressJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(createAddressJPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(createAddressJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(streetJLabel)
                    .addComponent(jTextField24, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(createAddressJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cityJLabel)
                    .addComponent(jTextField18, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(createAddressJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(stateJLabel)
                    .addComponent(jTextField17, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(createAddressJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(zipcodeJLabel)
                    .addComponent(jTextField20, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(160, 160, 160)
                .addComponent(submitJButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(119, Short.MAX_VALUE))
        );

        addressJSplitPane.setLeftComponent(createAddressJPanel);

        viewAddressJPanel.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        viewAddressJPanel.setAlignmentX(1.0F);
        viewAddressJPanel.setEnabled(false);
        viewAddressJPanel.setName(""); // NOI18N
        viewAddressJPanel.setPreferredSize(new java.awt.Dimension(200, 455));

        streetJLabel1.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        streetJLabel1.setText("Steet Address");

        jTextField33.setEnabled(false);
        jTextField33.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField33ActionPerformed(evt);
            }
        });

        cityJLabel1.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        cityJLabel1.setText("City");

        jTextField34.setEnabled(false);

        stateJLabel1.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        stateJLabel1.setText("State");

        jTextField35.setEnabled(false);

        zipcodeJLabel1.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        zipcodeJLabel1.setText("Zip Code");

        jTextField36.setEnabled(false);

        javax.swing.GroupLayout viewAddressJPanelLayout = new javax.swing.GroupLayout(viewAddressJPanel);
        viewAddressJPanel.setLayout(viewAddressJPanelLayout);
        viewAddressJPanelLayout.setHorizontalGroup(
            viewAddressJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(viewAddressJPanelLayout.createSequentialGroup()
                .addGap(75, 75, 75)
                .addGroup(viewAddressJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(viewAddressJPanelLayout.createSequentialGroup()
                        .addGroup(viewAddressJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(stateJLabel1)
                            .addComponent(cityJLabel1)
                            .addComponent(streetJLabel1))
                        .addGap(23, 23, 23)
                        .addGroup(viewAddressJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jTextField34)
                            .addComponent(jTextField35)
                            .addComponent(jTextField36)
                            .addComponent(jTextField33, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(zipcodeJLabel1))
                .addContainerGap(197, Short.MAX_VALUE))
        );
        viewAddressJPanelLayout.setVerticalGroup(
            viewAddressJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(viewAddressJPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(viewAddressJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(streetJLabel1)
                    .addComponent(jTextField33, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(viewAddressJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cityJLabel1)
                    .addComponent(jTextField34, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(viewAddressJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(stateJLabel1)
                    .addComponent(jTextField35, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(viewAddressJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(zipcodeJLabel1)
                    .addComponent(jTextField36, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(329, Short.MAX_VALUE))
        );

        addressJSplitPane.setRightComponent(viewAddressJPanel);

        addressJTabbedPane.addTab("tab1", addressJSplitPane);

        jTabbedPane1.addTab("Address Info", addressJTabbedPane);

        createSavingJPanel.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        createSavingJPanel.setEnabled(false);
        createSavingJPanel.setMaximumSize(new java.awt.Dimension(300, 445));
        createSavingJPanel.setMinimumSize(new java.awt.Dimension(300, 455));
        createSavingJPanel.setPreferredSize(new java.awt.Dimension(300, 455));

        sBanknameJLabel.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        sBanknameJLabel.setText("Bank Name");

        sRoutingNoJLabel.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        sRoutingNoJLabel.setText("Routing Number");

        sAccountNoJLabel.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        sAccountNoJLabel.setText("Account Number");

        sAccountBalanceJLabel.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        sAccountBalanceJLabel.setText("Account Balance");

        sAccountypeJLabel.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        sAccountypeJLabel.setText("Account (Type)");

        submitJButton2.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        submitJButton2.setText("Submit");
        submitJButton2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jTextField11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField11ActionPerformed(evt);
            }
        });

        jTextField16.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField16ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout createSavingJPanelLayout = new javax.swing.GroupLayout(createSavingJPanel);
        createSavingJPanel.setLayout(createSavingJPanelLayout);
        createSavingJPanelLayout.setHorizontalGroup(
            createSavingJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(createSavingJPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(createSavingJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(submitJButton2, javax.swing.GroupLayout.DEFAULT_SIZE, 286, Short.MAX_VALUE)
                    .addGroup(createSavingJPanelLayout.createSequentialGroup()
                        .addGroup(createSavingJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(sAccountNoJLabel)
                            .addComponent(sRoutingNoJLabel)
                            .addComponent(sBanknameJLabel)
                            .addComponent(sAccountypeJLabel))
                        .addGap(18, 18, 18)
                        .addGroup(createSavingJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jTextField10, javax.swing.GroupLayout.DEFAULT_SIZE, 115, Short.MAX_VALUE)
                            .addComponent(jTextField9, javax.swing.GroupLayout.DEFAULT_SIZE, 115, Short.MAX_VALUE)
                            .addComponent(jTextField12, javax.swing.GroupLayout.DEFAULT_SIZE, 115, Short.MAX_VALUE)
                            .addComponent(jTextField11, javax.swing.GroupLayout.DEFAULT_SIZE, 115, Short.MAX_VALUE)
                            .addComponent(jTextField16)))
                    .addComponent(sAccountBalanceJLabel)))
        );
        createSavingJPanelLayout.setVerticalGroup(
            createSavingJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(createSavingJPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(createSavingJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(sBanknameJLabel)
                    .addComponent(jTextField16, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(createSavingJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(sRoutingNoJLabel)
                    .addComponent(jTextField10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(createSavingJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(sAccountNoJLabel)
                    .addComponent(jTextField9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(createSavingJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(sAccountBalanceJLabel)
                    .addComponent(jTextField12, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(createSavingJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(sAccountypeJLabel)
                    .addComponent(jTextField11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(180, 180, 180)
                .addComponent(submitJButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(60, Short.MAX_VALUE))
        );

        savingJSplitPane.setLeftComponent(createSavingJPanel);

        viewSavingJPanel.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        viewSavingJPanel.setAlignmentX(1.0F);
        viewSavingJPanel.setEnabled(false);
        viewSavingJPanel.setMaximumSize(new java.awt.Dimension(200, 455));
        viewSavingJPanel.setMinimumSize(new java.awt.Dimension(200, 455));
        viewSavingJPanel.setName(""); // NOI18N
        viewSavingJPanel.setPreferredSize(new java.awt.Dimension(200, 455));

        sAccounttypeJLabel1.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        sAccounttypeJLabel1.setText("Account (Type)");

        sAccountBalanceJLabel1.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        sAccountBalanceJLabel1.setText("Account Balance");

        sAccountNoJLabel1.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        sAccountNoJLabel1.setText("Account Number");

        sRoutingNoJLabel1.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        sRoutingNoJLabel1.setText("Routing Number");

        sBanknameJLabel1.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        sBanknameJLabel1.setText("Bank Name");

        jTextField37.setEnabled(false);
        jTextField37.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField37ActionPerformed(evt);
            }
        });

        jTextField13.setEnabled(false);

        jTextField14.setEnabled(false);

        jTextField15.setEnabled(false);

        jTextField38.setEnabled(false);
        jTextField38.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField38ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout viewSavingJPanelLayout = new javax.swing.GroupLayout(viewSavingJPanel);
        viewSavingJPanel.setLayout(viewSavingJPanelLayout);
        viewSavingJPanelLayout.setHorizontalGroup(
            viewSavingJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(viewSavingJPanelLayout.createSequentialGroup()
                .addGap(57, 57, 57)
                .addGroup(viewSavingJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(viewSavingJPanelLayout.createSequentialGroup()
                        .addGroup(viewSavingJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(sAccountNoJLabel1)
                            .addComponent(sRoutingNoJLabel1)
                            .addComponent(sBanknameJLabel1)
                            .addComponent(sAccounttypeJLabel1))
                        .addGap(18, 18, 18)
                        .addGroup(viewSavingJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jTextField13)
                            .addComponent(jTextField14)
                            .addComponent(jTextField15)
                            .addComponent(jTextField38)
                            .addComponent(jTextField37, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(sAccountBalanceJLabel1))
                .addContainerGap(203, Short.MAX_VALUE))
        );
        viewSavingJPanelLayout.setVerticalGroup(
            viewSavingJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(viewSavingJPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(viewSavingJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(sBanknameJLabel1)
                    .addComponent(jTextField37, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(viewSavingJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(sRoutingNoJLabel1)
                    .addComponent(jTextField13, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(viewSavingJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(sAccountNoJLabel1)
                    .addComponent(jTextField14, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(viewSavingJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(sAccountBalanceJLabel1)
                    .addComponent(jTextField15, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(viewSavingJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(sAccounttypeJLabel1)
                    .addComponent(jTextField38, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(290, Short.MAX_VALUE))
        );

        savingJSplitPane.setRightComponent(viewSavingJPanel);

        savingJTabbedPane.addTab("tab1", savingJSplitPane);

        jTabbedPane1.addTab("Saving account  Info", savingJTabbedPane);

        createCheckingJPanel.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        createCheckingJPanel.setEnabled(false);
        createCheckingJPanel.setMaximumSize(new java.awt.Dimension(300, 445));
        createCheckingJPanel.setMinimumSize(new java.awt.Dimension(300, 455));

        cBanknameJLabel.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        cBanknameJLabel.setText("Bank Name");

        cRoutingNoJLabel.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        cRoutingNoJLabel.setText("Routing Number");

        cAccountNoJLabel.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        cAccountNoJLabel.setText("Account Number");

        cAccountBalanceJLabel.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        cAccountBalanceJLabel.setText("Account Balance");

        cAccountTypeJLabel.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        cAccountTypeJLabel.setText("Account (Type)");

        submitJButton4.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        submitJButton4.setText("Submit");
        submitJButton4.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        submitJButton4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                submitJButton4MouseClicked(evt);
            }
        });

        jTextField47.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField47ActionPerformed(evt);
            }
        });

        jTextField49.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField49ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout createCheckingJPanelLayout = new javax.swing.GroupLayout(createCheckingJPanel);
        createCheckingJPanel.setLayout(createCheckingJPanelLayout);
        createCheckingJPanelLayout.setHorizontalGroup(
            createCheckingJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(createCheckingJPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(createCheckingJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(submitJButton4, javax.swing.GroupLayout.DEFAULT_SIZE, 286, Short.MAX_VALUE)
                    .addGroup(createCheckingJPanelLayout.createSequentialGroup()
                        .addGroup(createCheckingJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cAccountNoJLabel)
                            .addComponent(cRoutingNoJLabel)
                            .addComponent(cBanknameJLabel)
                            .addComponent(cAccountTypeJLabel))
                        .addGap(18, 18, 18)
                        .addGroup(createCheckingJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jTextField46, javax.swing.GroupLayout.DEFAULT_SIZE, 115, Short.MAX_VALUE)
                            .addComponent(jTextField45, javax.swing.GroupLayout.DEFAULT_SIZE, 115, Short.MAX_VALUE)
                            .addComponent(jTextField48, javax.swing.GroupLayout.DEFAULT_SIZE, 115, Short.MAX_VALUE)
                            .addComponent(jTextField47, javax.swing.GroupLayout.DEFAULT_SIZE, 115, Short.MAX_VALUE)
                            .addComponent(jTextField49)))
                    .addComponent(cAccountBalanceJLabel)))
        );
        createCheckingJPanelLayout.setVerticalGroup(
            createCheckingJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(createCheckingJPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(createCheckingJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cBanknameJLabel)
                    .addComponent(jTextField49, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(createCheckingJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cRoutingNoJLabel)
                    .addComponent(jTextField46, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(createCheckingJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cAccountNoJLabel)
                    .addComponent(jTextField45, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(createCheckingJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cAccountBalanceJLabel)
                    .addComponent(jTextField48, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(createCheckingJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cAccountTypeJLabel)
                    .addComponent(jTextField47, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(165, 165, 165)
                .addComponent(submitJButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(75, Short.MAX_VALUE))
        );

        checkingJSplitPane.setLeftComponent(createCheckingJPanel);

        viewCheckingJPanel.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        viewCheckingJPanel.setAlignmentX(1.0F);
        viewCheckingJPanel.setEnabled(false);
        viewCheckingJPanel.setMaximumSize(new java.awt.Dimension(200, 455));
        viewCheckingJPanel.setMinimumSize(new java.awt.Dimension(200, 455));
        viewCheckingJPanel.setName(""); // NOI18N

        cAccounttypeJLabel1.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        cAccounttypeJLabel1.setText("Account (Type)");

        cAccountBalanceJLabel1.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        cAccountBalanceJLabel1.setText("Account Balance");

        cAccountNoJLabel1.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        cAccountNoJLabel1.setText("Account Number");

        cRoutingNoJLabel1.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        cRoutingNoJLabel1.setText("Routing Number");

        cBanknameJLabel1.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        cBanknameJLabel1.setText("Bank Name");

        jTextField50.setEnabled(false);
        jTextField50.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField50ActionPerformed(evt);
            }
        });

        jTextField51.setEnabled(false);

        jTextField52.setEnabled(false);

        jTextField53.setEnabled(false);

        jTextField54.setEnabled(false);
        jTextField54.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField54ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout viewCheckingJPanelLayout = new javax.swing.GroupLayout(viewCheckingJPanel);
        viewCheckingJPanel.setLayout(viewCheckingJPanelLayout);
        viewCheckingJPanelLayout.setHorizontalGroup(
            viewCheckingJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(viewCheckingJPanelLayout.createSequentialGroup()
                .addGap(57, 57, 57)
                .addGroup(viewCheckingJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(viewCheckingJPanelLayout.createSequentialGroup()
                        .addGroup(viewCheckingJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cAccountNoJLabel1)
                            .addComponent(cRoutingNoJLabel1)
                            .addComponent(cBanknameJLabel1)
                            .addComponent(cAccounttypeJLabel1))
                        .addGap(18, 18, 18)
                        .addGroup(viewCheckingJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jTextField51)
                            .addComponent(jTextField52)
                            .addComponent(jTextField53)
                            .addComponent(jTextField54)
                            .addComponent(jTextField50, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(cAccountBalanceJLabel1))
                .addContainerGap(203, Short.MAX_VALUE))
        );
        viewCheckingJPanelLayout.setVerticalGroup(
            viewCheckingJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(viewCheckingJPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(viewCheckingJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cBanknameJLabel1)
                    .addComponent(jTextField50, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(viewCheckingJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cRoutingNoJLabel1)
                    .addComponent(jTextField51, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(viewCheckingJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cAccountNoJLabel1)
                    .addComponent(jTextField52, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(viewCheckingJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cAccountBalanceJLabel1)
                    .addComponent(jTextField53, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(viewCheckingJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cAccounttypeJLabel1)
                    .addComponent(jTextField54, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(290, Short.MAX_VALUE))
        );

        checkingJSplitPane.setRightComponent(viewCheckingJPanel);

        checkingJTabbedPane.addTab("tab1", checkingJSplitPane);

        jTabbedPane1.addTab("Checking account Info", checkingJTabbedPane);

        createDriverJPanel.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        createDriverJPanel.setEnabled(false);
        createDriverJPanel.setMaximumSize(new java.awt.Dimension(300, 445));
        createDriverJPanel.setMinimumSize(new java.awt.Dimension(300, 455));

        licenseNoJLabel.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        licenseNoJLabel.setText("License Number");

        issuedDateJLabel.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        issuedDateJLabel.setText("Issued Date");

        expireDateJLabel.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        expireDateJLabel.setText("Expire Date");

        bloodJLabel.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        bloodJLabel.setText("Blood Type");

        photoJLabel.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        photoJLabel.setText("Personal Photo");

        submitJButton3.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        submitJButton3.setText("Submit");
        submitJButton3.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jTextField22.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField22ActionPerformed(evt);
            }
        });

        jTextField39.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField39ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout createDriverJPanelLayout = new javax.swing.GroupLayout(createDriverJPanel);
        createDriverJPanel.setLayout(createDriverJPanelLayout);
        createDriverJPanelLayout.setHorizontalGroup(
            createDriverJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(createDriverJPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(createDriverJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(submitJButton3, javax.swing.GroupLayout.DEFAULT_SIZE, 286, Short.MAX_VALUE)
                    .addGroup(createDriverJPanelLayout.createSequentialGroup()
                        .addGroup(createDriverJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(expireDateJLabel)
                            .addComponent(issuedDateJLabel)
                            .addComponent(licenseNoJLabel)
                            .addComponent(photoJLabel))
                        .addGap(18, 18, 18)
                        .addGroup(createDriverJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jTextField21, javax.swing.GroupLayout.DEFAULT_SIZE, 115, Short.MAX_VALUE)
                            .addComponent(jTextField19, javax.swing.GroupLayout.DEFAULT_SIZE, 115, Short.MAX_VALUE)
                            .addComponent(jTextField25, javax.swing.GroupLayout.DEFAULT_SIZE, 115, Short.MAX_VALUE)
                            .addComponent(jTextField22, javax.swing.GroupLayout.DEFAULT_SIZE, 115, Short.MAX_VALUE)
                            .addComponent(jTextField39)))
                    .addComponent(bloodJLabel)))
        );
        createDriverJPanelLayout.setVerticalGroup(
            createDriverJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(createDriverJPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(createDriverJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(licenseNoJLabel)
                    .addComponent(jTextField39, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(createDriverJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(issuedDateJLabel)
                    .addComponent(jTextField21, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(createDriverJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(expireDateJLabel)
                    .addComponent(jTextField19, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(createDriverJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bloodJLabel)
                    .addComponent(jTextField25, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(createDriverJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(photoJLabel)
                    .addComponent(jTextField22, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(165, 165, 165)
                .addComponent(submitJButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(75, Short.MAX_VALUE))
        );

        driverJSplitPane.setLeftComponent(createDriverJPanel);

        viewDriverJPanel.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        viewDriverJPanel.setAlignmentX(1.0F);
        viewDriverJPanel.setEnabled(false);
        viewDriverJPanel.setMaximumSize(new java.awt.Dimension(200, 455));
        viewDriverJPanel.setMinimumSize(new java.awt.Dimension(200, 455));
        viewDriverJPanel.setName(""); // NOI18N

        photoJLabel1.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        photoJLabel1.setText("Personal Photo");

        bloodJLabel1.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        bloodJLabel1.setText("Blood Type");

        expireDateJLabel1.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        expireDateJLabel1.setText("Expire Date");

        issuedDateJLabel1.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        issuedDateJLabel1.setText("Issued Date");

        licenseNoJLabel1.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        licenseNoJLabel1.setText("License Number");

        jTextField40.setEnabled(false);
        jTextField40.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField40ActionPerformed(evt);
            }
        });

        jTextField41.setEnabled(false);

        jTextField42.setEnabled(false);

        jTextField43.setEnabled(false);

        jTextField44.setEnabled(false);
        jTextField44.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField44ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout viewDriverJPanelLayout = new javax.swing.GroupLayout(viewDriverJPanel);
        viewDriverJPanel.setLayout(viewDriverJPanelLayout);
        viewDriverJPanelLayout.setHorizontalGroup(
            viewDriverJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(viewDriverJPanelLayout.createSequentialGroup()
                .addGap(57, 57, 57)
                .addGroup(viewDriverJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(viewDriverJPanelLayout.createSequentialGroup()
                        .addGroup(viewDriverJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(expireDateJLabel1)
                            .addComponent(issuedDateJLabel1)
                            .addComponent(licenseNoJLabel1)
                            .addComponent(photoJLabel1))
                        .addGap(18, 18, 18)
                        .addGroup(viewDriverJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jTextField41)
                            .addComponent(jTextField42)
                            .addComponent(jTextField43)
                            .addComponent(jTextField44)
                            .addComponent(jTextField40, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(bloodJLabel1))
                .addContainerGap(205, Short.MAX_VALUE))
        );
        viewDriverJPanelLayout.setVerticalGroup(
            viewDriverJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(viewDriverJPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(viewDriverJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(licenseNoJLabel1)
                    .addComponent(jTextField40, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(viewDriverJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(issuedDateJLabel1)
                    .addComponent(jTextField41, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(viewDriverJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(expireDateJLabel1)
                    .addComponent(jTextField42, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(viewDriverJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bloodJLabel1)
                    .addComponent(jTextField43, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(viewDriverJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(photoJLabel1)
                    .addComponent(jTextField44, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(290, Short.MAX_VALUE))
        );

        driverJSplitPane.setRightComponent(viewDriverJPanel);

        driverJTabbedPane.addTab("tab1", driverJSplitPane);

        jTabbedPane1.addTab("Driver's license Info", driverJTabbedPane);

        createMedicalJPanel.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        createMedicalJPanel.setEnabled(false);
        createMedicalJPanel.setMaximumSize(new java.awt.Dimension(300, 455));
        createMedicalJPanel.setMinimumSize(new java.awt.Dimension(250, 455));
        createMedicalJPanel.setPreferredSize(new java.awt.Dimension(300, 455));

        medicalNoJLabel.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        medicalNoJLabel.setText("Record Number ");

        alergy1JLabel.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        alergy1JLabel.setText("Alergy 1");

        alergy2JLabel.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        alergy2JLabel.setText("Alergy 2");

        alergy3JLabel.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        alergy3JLabel.setText("Alergy 3");

        submitJButton5.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        submitJButton5.setText("Submit");
        submitJButton5.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jTextField58.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField58ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout createMedicalJPanelLayout = new javax.swing.GroupLayout(createMedicalJPanel);
        createMedicalJPanel.setLayout(createMedicalJPanelLayout);
        createMedicalJPanelLayout.setHorizontalGroup(
            createMedicalJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(createMedicalJPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(createMedicalJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(submitJButton5, javax.swing.GroupLayout.DEFAULT_SIZE, 286, Short.MAX_VALUE)
                    .addGroup(createMedicalJPanelLayout.createSequentialGroup()
                        .addGroup(createMedicalJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(alergy2JLabel)
                            .addComponent(alergy1JLabel)
                            .addComponent(medicalNoJLabel))
                        .addGap(23, 23, 23)
                        .addGroup(createMedicalJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jTextField56, javax.swing.GroupLayout.DEFAULT_SIZE, 115, Short.MAX_VALUE)
                            .addComponent(jTextField55, javax.swing.GroupLayout.DEFAULT_SIZE, 115, Short.MAX_VALUE)
                            .addComponent(jTextField57, javax.swing.GroupLayout.DEFAULT_SIZE, 115, Short.MAX_VALUE)
                            .addComponent(jTextField58)))
                    .addComponent(alergy3JLabel)))
        );
        createMedicalJPanelLayout.setVerticalGroup(
            createMedicalJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(createMedicalJPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(createMedicalJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(medicalNoJLabel)
                    .addComponent(jTextField58, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(createMedicalJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(alergy1JLabel)
                    .addComponent(jTextField56, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(createMedicalJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(alergy2JLabel)
                    .addComponent(jTextField55, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(createMedicalJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(alergy3JLabel)
                    .addComponent(jTextField57, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(160, 160, 160)
                .addComponent(submitJButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(119, Short.MAX_VALUE))
        );

        jSplitPane1.setLeftComponent(createMedicalJPanel);

        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel1.setAlignmentX(1.0F);
        jPanel1.setEnabled(false);
        jPanel1.setPreferredSize(new java.awt.Dimension(200, 455));

        medicalNoJLabel1.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        medicalNoJLabel1.setText("Record Number ");

        alergy1JLabel1.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        alergy1JLabel1.setText("Alergy 1");

        alergy2JLabel1.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        alergy2JLabel1.setText("Alergy 2");

        alergy3JLabel1.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        alergy3JLabel1.setText("Alergy 3");

        jTextField59.setEnabled(false);

        jTextField60.setEnabled(false);

        jTextField61.setEnabled(false);

        jTextField62.setEnabled(false);
        jTextField62.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField62ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(53, 53, 53)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(alergy2JLabel1)
                            .addComponent(alergy1JLabel1)
                            .addComponent(alergy3JLabel1))
                        .addGap(76, 76, 76)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextField60, javax.swing.GroupLayout.DEFAULT_SIZE, 115, Short.MAX_VALUE)
                            .addComponent(jTextField61, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextField59, javax.swing.GroupLayout.DEFAULT_SIZE, 115, Short.MAX_VALUE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(medicalNoJLabel1)
                        .addGap(18, 18, 18)
                        .addComponent(jTextField62, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(209, Short.MAX_VALUE))
        );

        jPanel1Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {jTextField59, jTextField60, jTextField61, jTextField62});

        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(medicalNoJLabel1)
                    .addComponent(jTextField62, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(alergy1JLabel1)
                    .addComponent(jTextField61, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(alergy2JLabel1)
                    .addComponent(jTextField60, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(alergy3JLabel1)
                    .addComponent(jTextField59, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(329, Short.MAX_VALUE))
        );

        jPanel1Layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {jTextField59, jTextField60, jTextField61, jTextField62});

        jSplitPane1.setRightComponent(jPanel1);

        medicalJTabbedPane.addTab("tab1", jSplitPane1);

        jTabbedPane1.addTab("Medical Record", medicalJTabbedPane);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 830, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 576, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(85, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void firstnameJTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_firstnameJTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_firstnameJTextFieldActionPerformed

    private void jTextField6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField6ActionPerformed

    private void jTextField3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField3ActionPerformed

    private void jTabbedPane1ComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_jTabbedPane1ComponentShown
        // TODO add your handling code here:
    }//GEN-LAST:event_jTabbedPane1ComponentShown

    private void jTabbedPane1ComponentHidden(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_jTabbedPane1ComponentHidden
        // TODO add your handling code here:
    }//GEN-LAST:event_jTabbedPane1ComponentHidden

    private void jTextField24ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField24ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField24ActionPerformed

    private void jTextField11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField11ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField11ActionPerformed

    private void jTextField16ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField16ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField16ActionPerformed

    private void jTextField33ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField33ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField33ActionPerformed

    private void jTextField37ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField37ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField37ActionPerformed

    private void jTextField38ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField38ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField38ActionPerformed

    private void jTextField22ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField22ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField22ActionPerformed

    private void jTextField39ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField39ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField39ActionPerformed

    private void jTextField40ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField40ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField40ActionPerformed

    private void jTextField44ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField44ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField44ActionPerformed

    private void jTextField47ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField47ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField47ActionPerformed

    private void jTextField49ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField49ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField49ActionPerformed

    private void jTextField50ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField50ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField50ActionPerformed

    private void jTextField54ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField54ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField54ActionPerformed

    private void jTextField58ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField58ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField58ActionPerformed

    private void jTextField62ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField62ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField62ActionPerformed

    private void jTextField32ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField32ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField32ActionPerformed

    private void jTextField29ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField29ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField29ActionPerformed

    private void firstnameJTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_firstnameJTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_firstnameJTextField1ActionPerformed

    private void submitJButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_submitJButtonMouseClicked
        // TODO add your handling code here:
        
    }//GEN-LAST:event_submitJButtonMouseClicked

    private void submitJButton4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_submitJButton4MouseClicked

    }//GEN-LAST:event_submitJButton4MouseClicked

    private void submitJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submitJButtonActionPerformed
        // TODO add your handling code here:
        personProfile.getDemoInfo().setFirstName(firstnameJTextField.getText());
    }//GEN-LAST:event_submitJButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainJFrame().setVisible(true);
            }
        });
    }
    private PersonProfile personProfile;
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JSplitPane addressJSplitPane;
    private javax.swing.JTabbedPane addressJTabbedPane;
    private javax.swing.JLabel ageJLabel;
    private javax.swing.JLabel ageJLabel1;
    private javax.swing.JLabel alergy1JLabel;
    private javax.swing.JLabel alergy1JLabel1;
    private javax.swing.JLabel alergy2JLabel;
    private javax.swing.JLabel alergy2JLabel1;
    private javax.swing.JLabel alergy3JLabel;
    private javax.swing.JLabel alergy3JLabel1;
    private javax.swing.JLabel bloodJLabel;
    private javax.swing.JLabel bloodJLabel1;
    private javax.swing.JLabel cAccountBalanceJLabel;
    private javax.swing.JLabel cAccountBalanceJLabel1;
    private javax.swing.JLabel cAccountNoJLabel;
    private javax.swing.JLabel cAccountNoJLabel1;
    private javax.swing.JLabel cAccountTypeJLabel;
    private javax.swing.JLabel cAccounttypeJLabel1;
    private javax.swing.JLabel cBanknameJLabel;
    private javax.swing.JLabel cBanknameJLabel1;
    private javax.swing.JLabel cRoutingNoJLabel;
    private javax.swing.JLabel cRoutingNoJLabel1;
    private javax.swing.JSplitPane checkingJSplitPane;
    private javax.swing.JTabbedPane checkingJTabbedPane;
    private javax.swing.JLabel cityJLabel;
    private javax.swing.JLabel cityJLabel1;
    private javax.swing.JPanel createAddressJPanel;
    private javax.swing.JPanel createCheckingJPanel;
    private javax.swing.JPanel createDemoJPanel;
    private javax.swing.JPanel createDriverJPanel;
    private javax.swing.JPanel createMedicalJPanel;
    private javax.swing.JPanel createSavingJPanel;
    private javax.swing.JSplitPane demoJSplitPane;
    private javax.swing.JTabbedPane demoJTabbedPane;
    private javax.swing.JLabel doeJLabel;
    private javax.swing.JLabel doeJLabel1;
    private javax.swing.JSplitPane driverJSplitPane;
    private javax.swing.JTabbedPane driverJTabbedPane;
    private javax.swing.JLabel expireDateJLabel;
    private javax.swing.JLabel expireDateJLabel1;
    private javax.swing.JLabel firstnameJLabel;
    private javax.swing.JLabel firstnameJLabel1;
    private javax.swing.JTextField firstnameJTextField;
    private javax.swing.JTextField firstnameJTextField1;
    private javax.swing.JLabel heightJLabel;
    private javax.swing.JLabel heightJLabel1;
    private javax.swing.JLabel issuedDateJLabel;
    private javax.swing.JLabel issuedDateJLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSplitPane jSplitPane1;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField10;
    private javax.swing.JTextField jTextField11;
    private javax.swing.JTextField jTextField12;
    private javax.swing.JTextField jTextField13;
    private javax.swing.JTextField jTextField14;
    private javax.swing.JTextField jTextField15;
    private javax.swing.JTextField jTextField16;
    private javax.swing.JTextField jTextField17;
    private javax.swing.JTextField jTextField18;
    private javax.swing.JTextField jTextField19;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField20;
    private javax.swing.JTextField jTextField21;
    private javax.swing.JTextField jTextField22;
    private javax.swing.JTextField jTextField24;
    private javax.swing.JTextField jTextField25;
    private javax.swing.JTextField jTextField26;
    private javax.swing.JTextField jTextField28;
    private javax.swing.JTextField jTextField29;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField30;
    private javax.swing.JTextField jTextField31;
    private javax.swing.JTextField jTextField32;
    private javax.swing.JTextField jTextField33;
    private javax.swing.JTextField jTextField34;
    private javax.swing.JTextField jTextField35;
    private javax.swing.JTextField jTextField36;
    private javax.swing.JTextField jTextField37;
    private javax.swing.JTextField jTextField38;
    private javax.swing.JTextField jTextField39;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField40;
    private javax.swing.JTextField jTextField41;
    private javax.swing.JTextField jTextField42;
    private javax.swing.JTextField jTextField43;
    private javax.swing.JTextField jTextField44;
    private javax.swing.JTextField jTextField45;
    private javax.swing.JTextField jTextField46;
    private javax.swing.JTextField jTextField47;
    private javax.swing.JTextField jTextField48;
    private javax.swing.JTextField jTextField49;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTextField jTextField50;
    private javax.swing.JTextField jTextField51;
    private javax.swing.JTextField jTextField52;
    private javax.swing.JTextField jTextField53;
    private javax.swing.JTextField jTextField54;
    private javax.swing.JTextField jTextField55;
    private javax.swing.JTextField jTextField56;
    private javax.swing.JTextField jTextField57;
    private javax.swing.JTextField jTextField58;
    private javax.swing.JTextField jTextField59;
    private javax.swing.JTextField jTextField6;
    private javax.swing.JTextField jTextField60;
    private javax.swing.JTextField jTextField61;
    private javax.swing.JTextField jTextField62;
    private javax.swing.JTextField jTextField63;
    private javax.swing.JTextField jTextField7;
    private javax.swing.JTextField jTextField9;
    private javax.swing.JLabel lastnameJLabel;
    private javax.swing.JLabel lastnameJLabel1;
    private javax.swing.JLabel licenseNoJLabel;
    private javax.swing.JLabel licenseNoJLabel1;
    private javax.swing.JTabbedPane medicalJTabbedPane;
    private javax.swing.JLabel medicalNoJLabel;
    private javax.swing.JLabel medicalNoJLabel1;
    private javax.swing.JLabel phoneJLabel;
    private javax.swing.JLabel phoneJLabel1;
    private javax.swing.JLabel photoJLabel;
    private javax.swing.JLabel photoJLabel1;
    private javax.swing.JLabel sAccountBalanceJLabel;
    private javax.swing.JLabel sAccountBalanceJLabel1;
    private javax.swing.JLabel sAccountNoJLabel;
    private javax.swing.JLabel sAccountNoJLabel1;
    private javax.swing.JLabel sAccounttypeJLabel1;
    private javax.swing.JLabel sAccountypeJLabel;
    private javax.swing.JLabel sBanknameJLabel;
    private javax.swing.JLabel sBanknameJLabel1;
    private javax.swing.JLabel sRoutingNoJLabel;
    private javax.swing.JLabel sRoutingNoJLabel1;
    private javax.swing.JSplitPane savingJSplitPane;
    private javax.swing.JTabbedPane savingJTabbedPane;
    private javax.swing.JLabel ssnJLabel;
    private javax.swing.JLabel ssnJLabel1;
    private javax.swing.JLabel stateJLabel;
    private javax.swing.JLabel stateJLabel1;
    private javax.swing.JLabel streetJLabel;
    private javax.swing.JLabel streetJLabel1;
    private javax.swing.JButton submitJButton;
    private javax.swing.JButton submitJButton1;
    private javax.swing.JButton submitJButton2;
    private javax.swing.JButton submitJButton3;
    private javax.swing.JButton submitJButton4;
    private javax.swing.JButton submitJButton5;
    private javax.swing.JPanel viewAddressJPanel;
    private javax.swing.JPanel viewCheckingJPanel;
    private javax.swing.JPanel viewDemoJPanel;
    private javax.swing.JPanel viewDriverJPanel;
    private javax.swing.JPanel viewSavingJPanel;
    private javax.swing.JLabel weightJLabel;
    private javax.swing.JLabel weightJLabel1;
    private javax.swing.JLabel zipcodeJLabel;
    private javax.swing.JLabel zipcodeJLabel1;
    // End of variables declaration//GEN-END:variables
}
